// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3rs3drmE1j0mi6yEoFq8xJo7pw_4nJ3w',
    appId: '1:37918663319:android:2b694440549b3c932fbfd2',
    messagingSenderId: '37918663319',
    projectId: 'lawndre-1c357',
    storageBucket: 'lawndre-1c357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAfR5foSMXk3bDuVxOgyO9-XeRijzx8iM',
    appId: '1:37918663319:ios:26c9ec7a769b662c2fbfd2',
    messagingSenderId: '37918663319',
    projectId: 'lawndre-1c357',
    storageBucket: 'lawndre-1c357.appspot.com',
    iosBundleId: 'com.example.lawndreProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmUoNl8dryCKZpfT25tIrfbUym988vj_8',
    appId: '1:37918663319:web:113060924a93115c2fbfd2',
    messagingSenderId: '37918663319',
    projectId: 'lawndre-1c357',
    authDomain: 'lawndre-1c357.firebaseapp.com',
    storageBucket: 'lawndre-1c357.appspot.com',
    measurementId: 'G-JJK34SX8HK',
  );
}
